-- cdc_flight source schema.
--
-- Deliberately exercises the awkward corners of Postgres logical decoding so that
-- rubric items (type mapping, TOAST, no-PK tables, arrays/JSON, partitioning) have
-- something real to bite on from day one.

DROP SCHEMA IF EXISTS app CASCADE;
CREATE SCHEMA app;

-- Custom enum: Debezium emits these as strings; DuckDB has native ENUM.
DROP TYPE IF EXISTS app.order_status CASCADE;
CREATE TYPE app.order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled', 'refunded');

-- ---------------------------------------------------------------------------
-- 1. customers: bread-and-butter table WITH a primary key.
-- ---------------------------------------------------------------------------
CREATE TABLE app.customers (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_ref    uuid        NOT NULL DEFAULT gen_random_uuid(),
    name            text        NOT NULL,
    email           text        NOT NULL UNIQUE,
    signup_at       timestamptz NOT NULL DEFAULT now(),
    lifetime_value  numeric(18, 4) NOT NULL DEFAULT 0,
    is_active       boolean     NOT NULL DEFAULT true,
    prefs           jsonb       NOT NULL DEFAULT '{}'::jsonb,
    tags            text[]      NOT NULL DEFAULT '{}',
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2. orders: FK to customers, enum column, nested JSON, integer array.
-- ---------------------------------------------------------------------------
CREATE TABLE app.orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     bigint      NOT NULL REFERENCES app.customers (id) ON DELETE CASCADE,
    placed_at       timestamptz NOT NULL DEFAULT now(),
    status          app.order_status NOT NULL DEFAULT 'pending',
    total_amount    numeric(12, 2) NOT NULL,
    currency        char(3)     NOT NULL DEFAULT 'USD',
    line_items      jsonb       NOT NULL DEFAULT '[]'::jsonb,
    quantities      integer[]   NOT NULL DEFAULT '{}',
    note            text
);
CREATE INDEX ON app.orders (customer_id);

-- ---------------------------------------------------------------------------
-- 3. sensor_readings: NO primary key.
--    REPLICA IDENTITY FULL is the only way logical decoding can describe the
--    "old" tuple for UPDATE/DELETE here. Without it Postgres refuses to decode
--    updates/deletes on the table at all.
-- ---------------------------------------------------------------------------
CREATE TABLE app.sensor_readings (
    sensor_id       text        NOT NULL,
    reading_at      timestamptz NOT NULL DEFAULT now(),
    value           double precision NOT NULL,
    unit            text        NOT NULL DEFAULT 'C',
    meta            jsonb       NOT NULL DEFAULT '{}'::jsonb
);
ALTER TABLE app.sensor_readings REPLICA IDENTITY FULL;

-- ---------------------------------------------------------------------------
-- 4. documents: large text body that Postgres will push out-of-line into TOAST.
--    Left at REPLICA IDENTITY DEFAULT on purpose so that unchanged-TOAST
--    placeholders (__debezium_unavailable_value) show up in the baseline.
-- ---------------------------------------------------------------------------
CREATE TABLE app.documents (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text        NOT NULL,
    body            text        NOT NULL,          -- >8 kB payloads => TOASTed
    body_bytes      integer     NOT NULL DEFAULT 0,
    revision        integer     NOT NULL DEFAULT 1,
    updated_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE app.documents ALTER COLUMN body SET STORAGE EXTENDED;

-- ---------------------------------------------------------------------------
-- 5. wide_types: one row per exotic Postgres type, to pin down type mapping.
-- ---------------------------------------------------------------------------
CREATE TABLE app.wide_types (
    id                  integer PRIMARY KEY,
    col_smallint        smallint,
    col_integer         integer,
    col_bigint          bigint,
    col_real            real,
    col_double          double precision,
    col_numeric         numeric(30, 10),
    col_numeric_nan     numeric,              -- Postgres numeric supports 'NaN'
    col_boolean         boolean,
    col_char            char(8),
    col_varchar         varchar(64),
    col_text            text,
    col_bytea           bytea,
    col_date            date,
    col_time            time,
    col_timetz          timetz,
    col_timestamp       timestamp,
    col_timestamptz     timestamptz,
    col_interval        interval,
    col_uuid            uuid,
    col_json            json,
    col_jsonb           jsonb,
    col_int_array       integer[],
    col_text_array      text[],
    col_numeric_array   numeric(12, 2)[],
    col_inet            inet,
    col_cidr            cidr,
    col_macaddr         macaddr,
    col_money           money,
    col_bit             bit(8),
    col_enum            app.order_status,
    col_point           point,
    col_int4range       int4range,
    col_double_inf      double precision,     -- 'Infinity'
    col_double_nan      double precision      -- 'NaN'
);

-- ---------------------------------------------------------------------------
-- 6. audit_log: partitioned table (declarative range partitioning by month).
-- ---------------------------------------------------------------------------
CREATE TABLE app.audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamptz NOT NULL,
    actor       text        NOT NULL,
    action      text        NOT NULL,
    payload     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE TABLE app.audit_log_2026_06 PARTITION OF app.audit_log
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE app.audit_log_2026_07 PARTITION OF app.audit_log
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE app.audit_log_2026_08 PARTITION OF app.audit_log
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- ---------------------------------------------------------------------------
-- 7. Debezium's stock source signal collection for incremental snapshots.
--    It is deliberately text-shaped: the connector owns interpretation of the
--    `type`/`data` request and the Flight never fabricates a source row value.
-- ---------------------------------------------------------------------------
CREATE TABLE app.cdc_flight_signal (
    id      text PRIMARY KEY,
    type    text NOT NULL,
    data    text
);
ALTER TABLE app.cdc_flight_signal REPLICA IDENTITY FULL;

-- ---------------------------------------------------------------------------
-- Replication plumbing.
-- pgoutput is the built-in output plugin (no extension needed) and needs a
-- PUBLICATION. We create it explicitly rather than letting Debezium autocreate
-- it, so the set of replicated tables is version-controlled and auditable.
-- ---------------------------------------------------------------------------
DROP PUBLICATION IF EXISTS cdc_flight_pub;
CREATE PUBLICATION cdc_flight_pub FOR TABLE
    app.customers,
    app.orders,
    app.sensor_readings,
    app.documents,
    app.wide_types,
    app.audit_log,
    app.cdc_flight_signal
WITH (publish = 'insert, update, delete, truncate', publish_via_partition_root = true);
